on: workflow_dispatch
jobs:
  deploy-to-cocoapods:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "LIB_VERSION=$LIB_VERSION" >> $GITHUB_ENV
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
